### ISSUE TITLE
Compatible Usage with JS

### ISSUE THREAD

**Issue by MentalGear** [helixbass/vue-coffee-eslint-example#3] opened 2020-05-12 10:58 UTC
I would be interested in knowing if there was a way to have coffeescript eslint pass, when there's parallel normal js code in my source. Atm, lint will error out (even though code is functional).
Since I have not much experience with webpack and lint confirguration, maybe you could give me a hint on how to get both lint passed?

```
yarn run v1.22.4
$ vue-cli-service lint
error: Parsing error: unexpected // at src/main.js:
1 error found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by helixbass** [comment] 2020-05-12 14:53
This is the same question as https://github.com/helixbass/eslint-plugin-coffee/issues/27#issuecomment-613205211, and that's a more relevant place for discussion, so I'll close this

Basically I'm familiar with a way to configure ESLint for a hybrid JS/Coffeescript project (via `overrides`, see eg https://github.com/helixbass/eslint-plugin-coffee/issues/33), but not sure how you could do that in a Vue project

The issue is how you specify all three parsers to ESLint: Vue parser (`vue-eslint-parser`), normal JS parser, and Coffeescript parser (`eslint-plugin-coffee`)

At the moment I think your best workaround (if you don't have too much JS in your existing app) would be to rewrite the `.js` -> `.coffee` so it's just Vue + Coffeescript

**Closed as completed by helixbass** 2020-05-12 14:53 UTC
